### ISSUE TITLE
Improve documentation to include novice users

### ISSUE THREAD

**Issue by desilinguist** [for-ai/rl#9]
There's no documentation for this project at all which is less than ideal. Basically, this project assumes that you are extremely well-versed in reinforcement learning and can figure out how to run this codebase yourself by looking at the code. For example, I am a complete novice and I couldn't figure out how to easily try something out using this codebase once I had finished installation. Even the quick start section in the README is not a complete example.

I would recommend that you create actual documentation on readthedocs.org that explains what RL is, what this codebase does for RL compared to other things, and provide a complete end-to-end example on how to use this codebase. The rest of the API and the modules should also be documented clearly.

**Comment by alexanderimanicowenrivers** [comment]
This is also now complete https://github.com/for-ai/rl/pull/10 

Thanks!

**Comment by alexanderimanicowenrivers** [comment]
https://rl-codebase.readthedocs.io/en/latest/
